version: "3.9"

services:
  db:
    image: postgres:18-alpine
    container_name: wiz-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wiz-network  # Add this

  api:
    build: .
    container_name: wiz-user-service
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=3001
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_EXPIRES_IN=24h
      - JWT_REFRESH_SECRET=your-super-secret-refresh-key-change-this-in-production
      - JWT_REFRESH_EXPIRES_IN=7d
      - OTP_EXPIRY_MINUTES=10
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - NODE_ENV=development
      - LOCATION_SERVICE_GRPC_URL=wiz-location-service:50051  # Add this
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - wiz-network  # Add this

volumes:
  postgres_data:

networks:
  wiz-network:
    external: true  # Add this section