version: "3.9"

services:
  db:
    image: postgres:18-alpine
    container_name: wiz-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: wiz_car_rental
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: wiz-user-service
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=phonewai1234s
      - DB_NAME=wiz_car_rental
      - PORT=3001
    depends_on:
      - db

volumes:
  postgres_data: